import type { ShardSpec } from '../src/shard';

import { describe, expect, it } from 'vitest';

import { createApp, get } from '../src/app';
import { albRules, gatewayRoutes, nginxConf } from '../src/gateway';
import { policy, shardSpecs } from '../src/shard';

// Two shards standing in for a real app: a policy-carrying group and the
// catch-all. `routes` is inert here — every view dispatches on prefix, so
// the per-route table never enters the picture.
const heavy: ShardSpec = {
  id: 'heavy',
  prefix: '/heavy',
  routes: [],
  policy: { timeoutMs: 30000, streaming: true },
};

const light: ShardSpec = {
  id: 'light',
  prefix: '/',
  routes: [],
  policy: {},
};

describe('nginxConf', () => {
  it('golden — unix sockets by default, keepalive trio built in, policy mapped', () => {
    expect(nginxConf([heavy, light])).toEqual(
      [
        '# generated by s200/gateway',
        '',
        'upstream heavy {',
        '    server unix:/run/s200/heavy.sock;',
        '    keepalive 32;',
        '}',
        '',
        'upstream light {',
        '    server unix:/run/s200/light.sock;',
        '    keepalive 32;',
        '}',
        '',
        'location ^~ /heavy {',
        '    proxy_pass http://heavy;',
        '    proxy_http_version 1.1;',
        '    proxy_set_header Connection "";',
        '    proxy_read_timeout 30s;',
        '    proxy_buffering off;',
        '}',
        '',
        'location ^~ / {',
        '    proxy_pass http://light;',
        '    proxy_http_version 1.1;',
        '    proxy_set_header Connection "";',
        '}',
        '',
      ].join('\n')
    );
  });

  it('golden — port mode: portBase + input index, socketDir ignored', () => {
    expect(nginxConf([heavy, light], { socketDir: '/ignored', portBase: 8001 })).toEqual(
      [
        '# generated by s200/gateway',
        '',
        'upstream heavy {',
        '    server 127.0.0.1:8001;',
        '    keepalive 32;',
        '}',
        '',
        'upstream light {',
        '    server 127.0.0.1:8002;',
        '    keepalive 32;',
        '}',
        '',
        'location ^~ /heavy {',
        '    proxy_pass http://heavy;',
        '    proxy_http_version 1.1;',
        '    proxy_set_header Connection "";',
        '    proxy_read_timeout 30s;',
        '    proxy_buffering off;',
        '}',
        '',
        'location ^~ / {',
        '    proxy_pass http://light;',
        '    proxy_http_version 1.1;',
        '    proxy_set_header Connection "";',
        '}',
        '',
      ].join('\n')
    );
  });

  it('honors a custom socketDir and normalizes its trailing slash', () => {
    expect(nginxConf([heavy], { socketDir: '/tmp/sockets/' })).toContain(
      'server unix:/tmp/sockets/heavy.sock;'
    );
  });

  it('maps timeoutMs to an s-unit timeout, keeping fractional seconds', () => {
    expect(nginxConf([{ ...heavy, policy: { timeoutMs: 1500 } }])).toContain(
      'proxy_read_timeout 1.5s;'
    );
    expect(nginxConf([{ ...heavy, policy: {} }])).not.toContain('proxy_read_timeout');
    expect(nginxConf([{ ...heavy, policy: {} }])).not.toContain('proxy_buffering');
  });
});

describe('gatewayRoutes', () => {
  it('golden — rules sorted longest prefix first, identity knobs mapped', () => {
    expect(
      gatewayRoutes([light, heavy], {
        gatewayName: 'edge',
        namespace: 'prod',
        hostname: 'api.example.com',
      })
    ).toEqual(
      [
        '# generated by s200/gateway',
        'apiVersion: gateway.networking.k8s.io/v1',
        'kind: HTTPRoute',
        'metadata:',
        '  name: edge',
        '  namespace: prod',
        'spec:',
        '  parentRefs:',
        '  - name: edge',
        '  hostnames:',
        '  - api.example.com',
        '  rules:',
        '  - matches:',
        '    - path:',
        '        type: PathPrefix',
        '        value: /heavy',
        '      backendRefs:',
        '      - name: heavy',
        '        port: 80',
        '  - matches:',
        '    - path:',
        '        type: PathPrefix',
        '        value: /',
        '      backendRefs:',
        '      - name: light',
        '        port: 80',
        '',
      ].join('\n')
    );
  });

  it('golden — defaults: gateway s200, no namespace/hostname; empty specs yield no rules', () => {
    expect(gatewayRoutes([])).toEqual(
      [
        '# generated by s200/gateway',
        'apiVersion: gateway.networking.k8s.io/v1',
        'kind: HTTPRoute',
        'metadata:',
        '  name: s200',
        'spec:',
        '  parentRefs:',
        '  - name: s200',
        '  rules: []',
        '',
      ].join('\n')
    );
  });
});

describe('albRules', () => {
  it('golden — priorities ascend longest-prefix first, path-pattern covers prefix and subtree', () => {
    expect(
      albRules([light, heavy], {
        listenerArn: 'arn:aws:elasticloadbalancing:us-east-1:1:listener/app/edge/abc',
        targetGroupArns: {
          heavy: 'arn:aws:elasticloadbalancing:us-east-1:1:targetgroup/heavy/aaa',
          light: 'arn:aws:elasticloadbalancing:us-east-1:1:targetgroup/light/bbb',
        },
      })
    ).toEqual(
      [
        '[',
        '  {',
        '    "Priority": "1",',
        '    "Conditions": [',
        '      {',
        '        "Field": "path-pattern",',
        '        "Values": [',
        '          "/heavy",',
        '          "/heavy/*"',
        '        ]',
        '      }',
        '    ],',
        '    "Actions": [',
        '      {',
        '        "Type": "forward",',
        '        "TargetGroupArn": "arn:aws:elasticloadbalancing:us-east-1:1:targetgroup/heavy/aaa"',
        '      }',
        '    ],',
        '    "ListenerArn": "arn:aws:elasticloadbalancing:us-east-1:1:listener/app/edge/abc"',
        '  },',
        '  {',
        '    "Priority": "2",',
        '    "Conditions": [',
        '      {',
        '        "Field": "path-pattern",',
        '        "Values": [',
        '          "/*"',
        '        ]',
        '      }',
        '    ],',
        '    "Actions": [',
        '      {',
        '        "Type": "forward",',
        '        "TargetGroupArn": "arn:aws:elasticloadbalancing:us-east-1:1:targetgroup/light/bbb"',
        '      }',
        '    ],',
        '    "ListenerArn": "arn:aws:elasticloadbalancing:us-east-1:1:listener/app/edge/abc"',
        '  }',
        ']',
        '',
      ].join('\n')
    );
  });

  it('fails loudly when a shard has no target group mapping', () => {
    expect(() => albRules([heavy], { targetGroupArns: {} })).toThrow(
      "[s200/gateway] albRules: no targetGroupArn for shard 'heavy'"
    );
  });
});

describe('gateway views, shared contract', () => {
  it('rejects a prefix without a leading slash in every view, naming the offender', () => {
    const bad: ShardSpec = { id: 'bad', prefix: 'heavy', routes: [], policy: {} };
    expect(() => nginxConf([bad])).toThrow(
      `[s200/gateway] nginxConf: spec.prefix must start with '/' — got bad:'heavy'`
    );
    expect(() => gatewayRoutes([bad])).toThrow('[s200/gateway] gatewayRoutes');
    expect(() => albRules([bad])).toThrow('[s200/gateway] albRules');
  });

  it('orders equal-start prefixes longest-first across views', () => {
    const a: ShardSpec = { id: 'a', prefix: '/a', routes: [], policy: {} };
    const ab: ShardSpec = { id: 'ab', prefix: '/a/b', routes: [], policy: {} };
    const yaml = gatewayRoutes([a, ab]);
    expect(yaml.indexOf('value: /a/b')).toBeLessThan(yaml.indexOf('value: /a\n'));
    const rules = JSON.parse(
      albRules([a, ab], { targetGroupArns: { a: 'arn:a', ab: 'arn:ab' } })
    ) as { Priority: string; Conditions: { Field: string; Values: string[] }[] }[];
    expect(rules[0]!.Priority).toBe('1');
    expect(rules[0]!.Conditions[0]!.Values[0]).toBe('/a/b');
    expect(rules[1]!.Priority).toBe('2');
    expect(rules[1]!.Conditions[0]!.Values[0]).toBe('/a');
  });

  it('consumes real shardSpecs() output — the whole contract chain, end to end', () => {
    const app = createApp();
    get(app, '/heavy/render', () => new Response('ok'));
    get(app, '/healthz', () => new Response('ok'));
    policy(app, 'get', '/heavy/render', { timeoutMs: 30000, streaming: true });
    const specs = shardSpecs(app, [
      { id: 'heavy', prefix: '/heavy' },
      { id: 'edge', prefix: '/' },
    ]);

    const conf = nginxConf(specs);
    expect(conf).toContain('location ^~ /heavy {');
    expect(conf).toContain('proxy_read_timeout 30s;');
    expect(conf).toContain('proxy_buffering off;');
    expect(conf).toContain('location ^~ / {');

    const yaml = gatewayRoutes(specs);
    expect(yaml.indexOf('value: /heavy')).toBeLessThan(yaml.indexOf('value: /\n'));

    const rules = JSON.parse(
      albRules(specs, { targetGroupArns: { heavy: 'arn:h', edge: 'arn:e' } })
    ) as { Conditions: { Values: string[] }[] }[];
    expect(rules[0]!.Conditions[0]!.Values).toEqual(['/heavy', '/heavy/*']);
    expect(rules[1]!.Conditions[0]!.Values).toEqual(['/*']);
  });

  it('is deterministic — same specs in, byte-identical string out', () => {
    const targetGroups = { targetGroupArns: { heavy: 'arn:h', light: 'arn:l' } };
    expect(nginxConf([heavy, light])).toBe(nginxConf([heavy, light]));
    expect(gatewayRoutes([light, heavy])).toBe(gatewayRoutes([light, heavy]));
    expect(albRules([light, heavy], targetGroups)).toBe(albRules([light, heavy], targetGroups));
  });
});
