#!/usr/bin/env node
/**
 * Deno runtime smoke test.
 *
 * The core is runtime-agnostic Web Standard code, so the exact bundle the
 * node/bun smoke drives (dist/index.mjs) must also serve through Deno.serve.
 * Deno needs a real entry file, so this script writes a tiny one to the OS
 * tmpdir that imports the built core by file URL (same trick as the
 * s200-deno scenario in bench-http.mjs), spawns `deno run --allow-net` on
 * it, and asserts the core end to end with node's fetch:
 *
 *   - onion middleware stamps its header on the unwind
 *   - GET param route answers 200 with the JSON body
 *   - the default 404 fallback is JSON, and the onion unwind sees it
 *     (fallbacks materialize inside the chain)
 *   - HEAD falls back to the GET route: same status and headers, no body
 *
 * Auto-skips with one printed line when no deno binary is on PATH (never
 * throws) — CI installs deno, so the gate is real there.
 *
 * Run: node scripts/smoke-deno.mjs — exits 0 when every check passes (or
 * on skip), 1 otherwise.
 */
import { execSync, spawn } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

try {
  execSync('deno --version', { stdio: 'ignore' });
} catch {
  console.log('smoke-deno  skipped (deno not installed — install deno >= 2.x to run it locally)');
  process.exit(0);
}

const distUrl = new URL('../dist/index.mjs', import.meta.url).href;
const dir = mkdtempSync(join(tmpdir(), 's200-deno-smoke-'));
const entry = join(dir, 'serve.mjs');
writeFileSync(
  entry,
  `// Generated by scripts/smoke-deno.mjs — safe to delete.
import { createApp, use, get, json, handle } from ${JSON.stringify(distUrl)};

const app = createApp();

// Stamps the header on the unwind, after next() resolves: every response —
// the handler's, the 404 fallback, the HEAD rebuild — must exist by then.
use(app, async (ctx, next) => {
  await next();
  if (ctx.res !== undefined) {
    const headers = new Headers(ctx.res.headers);
    headers.set('x-s200', 'deno');
    ctx.res = new Response(ctx.res.body, {
      status: ctx.res.status,
      statusText: ctx.res.statusText,
      headers,
    });
  }
});

get(app, '/hello/:name', (ctx) => json(ctx, { hello: ctx.params.name }));

const server = Deno.serve(
  { port: 0, hostname: '127.0.0.1', onListen: ({ port }) => console.log(port) },
  (request) => handle(app, request),
);
await server.finished;
`,
);

const child = spawn('deno', ['run', '--allow-net', entry], {
  stdio: ['ignore', 'pipe', 'pipe'],
});
let stderr = '';
child.stderr.setEncoding('utf8');
child.stderr.on('data', (chunk) => {
  stderr += chunk;
});
let exited = false;
child.once('exit', () => {
  exited = true;
});
const cleanup = () => rmSync(dir, { recursive: true, force: true });
child.once('exit', cleanup);

// The entry prints its bound port as the first stdout line once listening.
const port = await new Promise((resolve, reject) => {
  const timer = setTimeout(
    () => reject(new Error(`smoke-deno: no port from deno within 30s\n${stderr}`)),
    30_000,
  );
  child.once('error', (error) => {
    clearTimeout(timer);
    reject(error);
  });
  child.stdout.setEncoding('utf8');
  child.stdout.on('data', (chunk) => {
    const line = chunk.trim().split('\n').at(-1);
    if (/^\d+$/.test(line)) {
      clearTimeout(timer);
      resolve(Number(line));
    }
  });
});

const stop = () =>
  new Promise((resolve) => {
    if (exited) {
      cleanup();
      return resolve();
    }
    child.once('exit', () => resolve());
    child.kill('SIGTERM');
  });

let failures = 0;
function check(name, ok, detail) {
  if (ok) {
    console.log(`ok   ${name}`);
  } else {
    failures += 1;
    console.error(`FAIL ${name} — ${detail}`);
  }
}

const base = `http://127.0.0.1:${port}`;
try {
  const hello = await fetch(`${base}/hello/deno`);
  const helloBody = await hello.json();
  check('GET /hello/:name status 200', hello.status === 200, `got ${hello.status}`);
  check(
    'GET /hello/:name body {"hello":"deno"}',
    JSON.stringify(helloBody) === '{"hello":"deno"}',
    JSON.stringify(helloBody),
  );
  check(
    'onion middleware header on route hit',
    hello.headers.get('x-s200') === 'deno',
    `got ${hello.headers.get('x-s200')}`,
  );

  const missing = await fetch(`${base}/nope`);
  const missingBody = await missing.json();
  check('GET /nope falls back to 404', missing.status === 404, `got ${missing.status}`);
  check(
    '404 fallback body {"error":"Not Found"}',
    JSON.stringify(missingBody) === '{"error":"Not Found"}',
    JSON.stringify(missingBody),
  );
  check(
    'onion unwind sees the in-chain 404',
    missing.headers.get('x-s200') === 'deno',
    `got ${missing.headers.get('x-s200')}`,
  );

  const head = await fetch(`${base}/hello/deno`, { method: 'HEAD' });
  const headBody = await head.text();
  const headLength = head.headers.get('content-length');
  check('HEAD /hello/:name falls back to the GET route', head.status === 200, `got ${head.status}`);
  check(
    'HEAD carries no body but keeps content-length',
    headBody === '' &&
      headLength !== null &&
      headLength === hello.headers.get('content-length'),
    `body ${JSON.stringify(headBody)}, content-length ${headLength}`,
  );
} catch (error) {
  failures += 1;
  console.error(`FAIL deno server unreachable — ${String(error)}\n${stderr}`);
} finally {
  await stop();
}

if (failures > 0) {
  console.error(`\nsmoke-deno FAILED — ${failures} check(s) failed\n${stderr}`);
  process.exit(1);
}
console.log('\nsmoke-deno OK — all checks passed on deno');
