/**
 * Standalone client code generation — `generateClient(app)` returns the
 * TypeScript source of a self-contained client module derived from the
 * app's runtime route table (the "app is data" payoff for codegen: no
 * build-time plugin, no reflection — the table is the spec). The emitted
 * module's only s200 touch is a types-only `ParamsOf` import; the path
 * filling and query-string logic are emitted inline, so the generated
 * file runs anywhere web fetch runs, with no s200 in `node_modules`.
 *
 * Output is deterministic — registration order, no timestamps — so it
 * diffs and commits like hand-written source.
 *
 * @module
 */

import type { App } from './app';

import { createRouteTable } from './route-table';

/** Options for {@link generateClient}. */
export type GenerateClientOptions = {
  /** Name of the emitted factory function. @default 'createClient' */
  name?: string;
  /** Baked-in default for the emitted `baseUrl` parameter. */
  baseUrl?: string;
  /** Name of the emitted fetcher parameter. @default 'fetcher' */
  fetcherName?: string;
};

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function capitalize(word: string): string {
  return word === '' ? '' : word[0]!.toUpperCase() + word.slice(1);
}

/**
 * One pattern segment's contribution to a method name: `:id` → `Id`,
 * `:id?` → `Id`, `*path` → `Path`; static segments capitalize each
 * alphanumeric run (`user-list` → `UserList`).
 */
function segmentNamePart(segment: string): string {
  if (segment.startsWith(':')) {
    return capitalize(segment.endsWith('?') ? segment.slice(1, -1) : segment.slice(1));
  }
  if (segment.startsWith('*')) {
    return capitalize(segment.slice(1));
  }
  let part = '';
  for (const piece of segment.split(/[^A-Za-z0-9]+/)) {
    part += capitalize(piece);
  }
  return part;
}

/**
 * camelCase method name: lowercased HTTP method plus capitalized segments
 * (`GET /api/v1/users` → `getApiV1Users`).
 */
function routeMethodName(method: string, pattern: string): string {
  let name = method.toLowerCase().replace(/[^A-Za-z0-9_$]/g, '');
  for (const segment of pattern.split('/')) {
    if (segment !== '') {
      name += segmentNamePart(segment);
    }
  }
  return /^[A-Za-z_$]/.test(name) ? name : `_${name}`;
}

/**
 * Whether a pattern captures anything (`:name`, `:name?`, `*name`) — such
 * routes take an `args` first argument; the rest take only `init`.
 */
function patternHasCaptures(pattern: string): boolean {
  return pattern.split('/').some(
    (segment) => segment !== '' && (segment.startsWith(':') || segment.startsWith('*'))
  );
}

/** Emits a single-quoted TypeScript string literal. */
function tsString(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

// Emitted-file header: the honest contract — the route table is runtime
// data, so no body types exist; every method returns Promise<Response>.
const HEADER = [
  '/**',
  ' * Generated by s200/codegen — do not edit by hand.',
  ' *',
  ' * One typed call per route registered at generation time (registration',
  ' * order). The route table is runtime data, so no request or response body',
  ' * types exist for it: every method returns Promise<Response> — read bodies',
  ' * with .json() or .text(). For compile-time-typed bodies, use createClient',
  " * from 's200/client' against the app itself.",
  ' */',
].join('\n');

const QUERY_TYPE = [
  '/** Query-string values: arrays repeat the key, undefined is skipped,',
  ' * numbers and booleans stringify (mirrors s200/client). */',
  'type Query = Record<',
  '  string,',
  '  string | number | boolean | readonly (string | number | boolean)[] | undefined',
  '>;',
].join('\n');

const CLIENT_INIT_TYPE = [
  '/** RequestInit plus query-string sugar — a structural twin of s200\'s',
  ' * ClientInit, emitted locally so this module has no s200 types beyond',
  ' * ParamsOf. */',
  'export type ClientInit = RequestInit & { query?: Query };',
].join('\n');

// Emitted once per module, used by every method. Mirrors s200/client's
// buildPathFn: percent-encoding of substituted values, wildcards keep
// their slashes piece-wise encoded, absent optionals drop out entirely.
const FILL = [
  '/**',
  ' * Fills a route pattern against base: static segments verbatim, :name,',
  ' * :name? and *name substituted from args (URL-encoded; wildcard values',
  ' * keep their slashes, each piece encoded). Absent optional segments drop',
  ' * out entirely — a missing required param throws. The query record is',
  ' * appended as a search string.',
  ' */',
  'export function fill(',
  '  pattern: string,',
  '  args: Record<string, string> | undefined,',
  '  base: string,',
  '  query: Query | undefined',
  '): string {',
  '  let url = base;',
  "  for (const part of pattern.split('/')) {",
  "    if (part === '') {",
  '      continue;',
  '    }',
  "    if (part.startsWith(':')) {",
  "      const optional = part.endsWith('?');",
  '      const name = optional ? part.slice(1, -1) : part.slice(1);',
  '      const value = args === undefined ? undefined : args[name];',
  '      if (value === undefined) {',
  '        if (optional) {',
  '          continue;',
  '        }',
  "        throw new Error(`Missing param '${name}' for route '${pattern}'`);",
  '      }',
  "      url += '/' + encodeURIComponent(value);",
  "    } else if (part.startsWith('*')) {",
  '      const name = part.slice(1);',
  '      const value = args === undefined ? undefined : args[name];',
  '      if (value === undefined) {',
  "        throw new Error(`Missing param '${name}' for route '${pattern}'`);",
  '      }',
  "      url += '/' + value.split('/').map(encodeURIComponent).join('/');",
  '    } else {',
  "      url += '/' + part;",
  '    }',
  '  }',
  '  if (query !== undefined) {',
  '    const search = new URLSearchParams();',
  '    for (const [name, value] of Object.entries(query)) {',
  '      if (value === undefined) {',
  '        continue;',
  '      }',
  '      if (Array.isArray(value)) {',
  '        for (const item of value) {',
  '          search.append(name, String(item));',
  '        }',
  '      } else {',
  '        search.append(name, String(value));',
  '      }',
  '    }',
  '    const qs = search.toString();',
  "    if (qs !== '') {",
  "      url += '?' + qs;",
  '    }',
  '  }',
  '  return url;',
  '}',
].join('\n');

/**
 * Emits a standalone TypeScript client module for `app`'s current route
 * table: one frozen-object method per registered route — params typed via
 * `ParamsOf`, the HTTP method baked into each call (never the caller's
 * job), query sugar mirrored from `s200/client`. `ALL` routes are skipped
 * (the runtime table cannot know which method you want) and listed in a
 * trailing comment instead.
 */
export function generateClient(app: App, options: GenerateClientOptions = {}): string {
  const factoryName = options.name ?? 'createClient';
  const fetcherName = options.fetcherName ?? 'fetcher';
  for (const [option, value] of [
    ['name', factoryName],
    ['fetcherName', fetcherName],
  ] as const) {
    if (!IDENTIFIER.test(value)) {
      throw new Error(
        `generateClient: options.${option} must be a valid TypeScript identifier, got '${value}'`
      );
    }
  }

  const table = createRouteTable(app);
  const used = new Set<string>();
  const methods: string[] = [];
  const skippedAll: string[] = [];
  for (const route of table.routes) {
    if (route.method === 'ALL') {
      skippedAll.push(route.pattern);
      continue;
    }
    const base = routeMethodName(route.method, route.pattern);
    let name = base;
    let suffix = 2;
    while (used.has(name)) {
      name = `${base}_${suffix}`;
      suffix += 1;
    }
    used.add(name);
    const patternLiteral = tsString(route.pattern);
    const methodLiteral = tsString(route.method);
    methods.push(
      patternHasCaptures(route.pattern)
        ? `    ${name}: (args: ParamsOf<${patternLiteral}>, init?: ClientInit): Promise<Response> =>
      ${fetcherName}(fill(${patternLiteral}, args, base, init?.query), { ...init, method: ${methodLiteral} }),`
        : `    ${name}: (init?: ClientInit): Promise<Response> =>
      ${fetcherName}(fill(${patternLiteral}, undefined, base, init?.query), { ...init, method: ${methodLiteral} }),`
    );
  }

  const total = table.routes.length;
  const skippedNote =
    skippedAll.length === 0
      ? ''
      : ` (${skippedAll.length} ALL-method route${skippedAll.length === 1 ? '' : 's'} listed below)`;
  const factoryDoc = `/** Generated from ${total} route${total === 1 ? '' : 's'}${skippedNote}. */`;
  const baseUrlDefault = options.baseUrl === undefined ? '' : ` = ${tsString(options.baseUrl)}`;
  const factory: string[] = [
    `export function ${factoryName}(baseUrl: string${baseUrlDefault}, ${fetcherName}: typeof fetch = fetch) {`,
  ];
  if (methods.length > 0) {
    factory.push(
      "  const base = baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl;",
      '  return Object.freeze({',
      ...methods,
      '  });',
    );
  } else {
    factory.push(
      '  // No method-specific routes were registered at generation time.',
      '  return Object.freeze({});',
    );
  }
  factory.push('}');

  const parts: string[] = [HEADER];
  // ParamsOf is only referenced by method signatures; an empty module
  // must not carry an unused type import (noUnusedLocals cleanliness).
  if (methods.length > 0) {
    parts.push("import type { ParamsOf } from 's200';");
  }
  parts.push(QUERY_TYPE, CLIENT_INIT_TYPE, FILL, `${factoryDoc}\n${factory.join('\n')}`);
  if (skippedAll.length > 0) {
    parts.push(
      [
        '// ALL-method routes are skipped above — the runtime table cannot know',
        '// which HTTP method you want for them. Call fetch (or your own',
        '// fetcher) directly for these:',
        ...skippedAll.map((pattern) => `//   ALL ${pattern}`),
      ].join('\n')
    );
  }
  return `${parts.join('\n\n')}\n`;
}
