/**
 * Gateway configuration views for the shard contract: `shardSpecs`
 * (`s200/shard`) distills an app into pure `ShardSpec` data, and these
 * generators compile that data into the config surfaces a fleet actually
 * runs — an nginx reverse-proxy config, a Gateway API `HTTPRoute`, and
 * AWS ALB listener rules. One routing truth, three deploy targets, and
 * zero scheduling decisions made here: the views say exactly what the
 * specs already say.
 *
 * Every generator is a pure string function — same specs in, byte-for-
 * byte same string out, no IO — so the output is golden-testable and
 * safe to hand to config management or diff in CI. Prefixes are always
 * rendered literally (nginx `^~` locations, Gateway API `PathPrefix`
 * matches, ALB `path-pattern` globs); regex locations are never emitted,
 * because shard prefixes are plain path data, not patterns.
 *
 * @module
 */

import type { ShardSpec } from './shard';

/** Provenance line every text view opens with — generated files should never be hand-edited silently. */
const GENERATED = '# generated by s200/gateway';

/** Options for {@link nginxConf}: unix-socket directory (default) or a TCP port base. */
export type NginxConfOptions = {
  /**
   * Directory holding the per-shard unix sockets (`${id}.sock`);
   * defaults to `/run/s200`. Trailing slashes are normalized away.
   */
  readonly socketDir?: string;
  /**
   * First TCP port — shard i (by input order) is addressed as
   * `127.0.0.1:(portBase + i)`. Omit to route over unix sockets.
   */
  readonly portBase?: number;
};

/** Options for {@link gatewayRoutes}: the identity and attachment knobs of the single emitted HTTPRoute. */
export type GatewayRoutesOptions = {
  /** Written into `metadata.namespace`; omit for the cluster default. */
  readonly namespace?: string;
  /** Gateway to attach to, and the route's own resource name; defaults to `s200`. */
  readonly gatewayName?: string;
  /** Written into `spec.hostnames`; omit to match every host. */
  readonly hostname?: string;
};

/** Options for {@link albRules}: which listener the rules belong to and where each shard forwards. */
export type AlbRulesOptions = {
  /** Written into every rule when present, so the JSON round-trips with its listener. */
  readonly listenerArn?: string;
  /**
   * Shard id → target group ARN. Every shard needs one: a rule that
   * forwards nowhere fails here, at generation, instead of at apply.
   */
  readonly targetGroupArns?: Record<string, string>;
};

/**
 * Rejects specs whose prefix is not an absolute path. All three views
 * are literal-prefix semantics (`^~`, `PathPrefix`, `path-pattern`), so
 * a prefix without the leading slash would silently match nothing.
 * Names every offender instead of guessing a fix.
 */
function requireSlashPrefixes(specs: readonly ShardSpec[], view: string): void {
  const bad = specs.filter((spec) => !spec.prefix.startsWith('/'));
  if (bad.length > 0) {
    const listed = bad.map((spec) => `${spec.id}:'${spec.prefix}'`).join(', ');
    throw new Error(
      `[s200/gateway] ${view}: spec.prefix must start with '/' — got ${listed}`
    );
  }
}

/**
 * Longest prefix first. Gateway API evaluates rules top-down and ALB by
 * ascending priority, so the most specific shard must always come first;
 * the sort is stable, so equal-length prefixes keep input order.
 */
function longestFirst(specs: readonly ShardSpec[]): readonly ShardSpec[] {
  return [...specs].sort((a, b) => b.prefix.length - a.prefix.length);
}

/** Milliseconds as an nginx time value with an `s` unit: `30000` → `30s`, `1500` → `1.5s`. */
function secondsOf(ms: number): string {
  return `${ms / 1000}s`;
}

/**
 * Bare words YAML 1.1 would load as booleans or null — a shard or
 * namespace literally named `no` must stay a string, so exactly those
 * scalars get single-quoted and everything else renders plain.
 */
const YAML_AMBIGUOUS = new Set([
  'y', 'Y', 'yes', 'Yes', 'YES', 'n', 'N', 'no', 'No', 'NO',
  'true', 'True', 'TRUE', 'false', 'False', 'FALSE',
  'on', 'On', 'ON', 'off', 'Off', 'OFF',
  'null', 'Null', 'NULL', '~',
]);

/** Renders a string as a YAML scalar, quoting the YAML 1.1 boolean/null words. */
function yamlScalar(value: string): string {
  return YAML_AMBIGUOUS.has(value) ? `'${value}'` : value;
}

/**
 * ALB `path-pattern` values for one prefix: the bare prefix plus the
 * subtree glob (ALB globs have no implicit prefix semantics). The
 * catch-all shard collapses to the single glob that spans everything.
 */
function pathPatternsOf(prefix: string): string[] {
  return prefix === '/' ? ['/*'] : [prefix, `${prefix}/*`];
}

/**
 * Renders the nginx view: one `upstream` block per shard (unix socket,
 * or `portBase + i` in TCP mode) and one `^~` location per prefix, in
 * input order — nginx resolves `^~` by longest literal prefix itself.
 *
 * Keepalive is built in, not an option: `keepalive 32` in the upstream
 * plus `proxy_http_version 1.1` and a cleared `Connection` header in
 * every location. Drop any one of the three and nginx closes the
 * upstream connection after each request, paying a full handshake per
 * proxied call. Policy mapping: `timeoutMs` → `proxy_read_timeout`,
 * `streaming` → `proxy_buffering off`; a shard without the policy
 * field simply omits the directive.
 */
export function nginxConf(
  specs: readonly ShardSpec[],
  opts: NginxConfOptions = {}
): string {
  requireSlashPrefixes(specs, 'nginxConf');
  const socketDir = (opts.socketDir ?? '/run/s200').replace(/\/+$/, '');
  const blocks: string[] = [GENERATED];
  for (const [i, spec] of specs.entries()) {
    const server =
      opts.portBase === undefined
        ? `unix:${socketDir}/${spec.id}.sock`
        : `127.0.0.1:${opts.portBase + i}`;
    blocks.push(`upstream ${spec.id} {\n    server ${server};\n    keepalive 32;\n}`);
  }
  for (const spec of specs) {
    const lines = [
      `location ^~ ${spec.prefix} {`,
      `    proxy_pass http://${spec.id};`,
      '    proxy_http_version 1.1;',
      '    proxy_set_header Connection "";',
    ];
    if (spec.policy.timeoutMs !== undefined) {
      lines.push(`    proxy_read_timeout ${secondsOf(spec.policy.timeoutMs)};`);
    }
    if (spec.policy.streaming === true) {
      lines.push('    proxy_buffering off;');
    }
    lines.push('}');
    blocks.push(lines.join('\n'));
  }
  return `${blocks.join('\n\n')}\n`;
}

/**
 * Renders the Gateway API view: a single `HTTPRoute` with one rule per
 * shard — a `PathPrefix` match on the shard prefix and a `backendRef`
 * to a Service named after the shard id (port 80; the Service object,
 * not the route, owns the real port). Rules are emitted longest prefix
 * first, because Gateway API evaluates them top-down and the first
 * match wins.
 */
export function gatewayRoutes(
  specs: readonly ShardSpec[],
  opts: GatewayRoutesOptions = {}
): string {
  requireSlashPrefixes(specs, 'gatewayRoutes');
  const gateway = opts.gatewayName ?? 's200';
  const lines = [
    GENERATED,
    'apiVersion: gateway.networking.k8s.io/v1',
    'kind: HTTPRoute',
    'metadata:',
    `  name: ${yamlScalar(gateway)}`,
  ];
  if (opts.namespace !== undefined) {
    lines.push(`  namespace: ${yamlScalar(opts.namespace)}`);
  }
  lines.push('spec:', '  parentRefs:', `  - name: ${yamlScalar(gateway)}`);
  if (opts.hostname !== undefined) {
    lines.push('  hostnames:', `  - ${yamlScalar(opts.hostname)}`);
  }
  if (specs.length === 0) {
    lines.push('  rules: []');
    return `${lines.join('\n')}\n`;
  }
  lines.push('  rules:');
  for (const spec of longestFirst(specs)) {
    lines.push(
      '  - matches:',
      '    - path:',
      '        type: PathPrefix',
      `        value: ${spec.prefix}`,
      '      backendRefs:',
      `      - name: ${yamlScalar(spec.id)}`,
      '        port: 80'
    );
  }
  return `${lines.join('\n')}\n`;
}

/**
 * Renders the AWS ALB view: one listener rule per shard, `path-pattern`
 * conditions on the prefix, `forward` to the shard's target group.
 * Priorities ascend from 1 in longest-prefix order — ALB evaluates the
 * lowest priority first, so the most specific shard must land on 1. A
 * shard without a `targetGroupArns` entry fails here with its id, not
 * at apply time with a mystery ARN error.
 */
export function albRules(
  specs: readonly ShardSpec[],
  opts: AlbRulesOptions = {}
): string {
  requireSlashPrefixes(specs, 'albRules');
  const rules = longestFirst(specs).map((spec, i) => {
    const targetGroupArn = opts.targetGroupArns?.[spec.id];
    if (targetGroupArn === undefined) {
      throw new Error(
        `[s200/gateway] albRules: no targetGroupArn for shard '${spec.id}' — pass opts.targetGroupArns['${spec.id}']`
      );
    }
    return {
      Priority: String(i + 1),
      Conditions: [{ Field: 'path-pattern', Values: pathPatternsOf(spec.prefix) }],
      Actions: [{ Type: 'forward', TargetGroupArn: targetGroupArn }],
      ...(opts.listenerArn === undefined ? {} : { ListenerArn: opts.listenerArn }),
    };
  });
  return `${JSON.stringify(rules, null, 2)}\n`;
}
